[workspace]
members = [
    "crypto",
    "crypto_core",
    "crypto_full",
    "sdk-common",
    "implementation/js/sentc_wasm",
    "implementation/dart/sentc_flutter_rust"
]

[profile.release]
lto = true

[profile.release.package.sentc_wasm]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
codegen-units = 1