[workspace]
members = [
    "crypto",
    "crypto_core",
    "crypto_full",
    "implementation/js/sentc_wasm",
    "implementation/dart/sentc_flutter_rust"
]

[workspace.dependencies]
sentc-crypto-common = "0.9.0"
#sentc-crypto-common = { path = "../backend/sentc-api/sdk-common" }    # for local dev

sentc-crypto = {version = "0.9.0", path = "crypto", default-features = false}
sentc-crypto-full = {version = "0.9.0", path = "crypto_full"}

[profile.dev]
# Must always use panic = "abort" to avoid needing to define the unstable eh_personality lang item.
panic = "abort"

[profile.release]
lto = true
panic = "abort"
strip = true

[profile.release.package.sentc_wasm]
opt-level = "z"
overflow-checks = true
debug = 0
debug-assertions = false
codegen-units = 1