[workspace]
members = [
    "crypto",
    "crypto_core",
    "crypto_common",
    "implementation/js/sentc_wasm",
    "implementation/dart/sendclose/rust",
    "implementation/dart/sentc/rust"
]

[profile.release]
lto = true