[workspace]
members = [
    "crypto",
    "crypto_core",
    "crypto_full",
    "sdk-common",
    "implementation/js/sentc_wasm",
    "implementation/dart/sentc_flutter_rust"
]

[profile.dev]
# Must always use panic = "abort" to avoid needing to define the unstable eh_personality lang item.
panic = "abort"

[profile.release]
lto = true
panic = "abort"
strip = true

[profile.release.package.sentc_wasm]
opt-level = "z"
overflow-checks = true
debug = 0
debug-assertions = false
codegen-units = 1