[package]
name = "sentc-crypto-full"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# own crypto lib
sentc-crypto = {version = "0.1.0", path = "../crypto", default-features = false}

sentc-crypto-common = {version = "0.1.0", path = "../sdk-common"}

reqwest = "0.11.11"

[features]
default = ["sentc-crypto/default"]
rust = ["sentc-crypto/rust"]