[package]
name = "sentc-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentc-crypto-core = {version = "0.1.0", path = "../crypto_core"}
sentc-crypto-common = {version = "0.1.0", path = "../sdk-common"}

# key and data export
base64ct = {version = "1.0.1", default-features = false, features = ["alloc"]}  # must use this version because it is not comp. with password_hash from argon2
pem-rfc7468 = {version = "0.3.1", features = ["alloc"]}

# json handling
serde_json = {version = "1.0.81", default-features = false, features = ["alloc"], optional = true}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"]}

[features]
default = ["serde_json"]
server = []
server_test = []
rust = []