[package]
name = "sendclose_crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
p256 = { version = "0.11.0", default-features = false, features = ["ecdh"] }
rand_core = { version = "0.6.3", default-features = false, features = ["getrandom"] }
