[package]
name = "sendclose_crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
# pre here because we must use rand_core version 0.6.3 under the hood but the actual version of x25519-dalek uses version 0.5
x25519-dalek = "2.0.0-pre.1"
rand_core = { version = "0.6.3", default-features = false, features = ["getrandom"] }
sha2 = "0.10.2"
hkdf = "0.12.3"