[package]
name = "sendclose-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sendclose-crypto-core = {version = "0.1.0", path = "../crypto_core"}
sendclose-crypto-common = {version = "0.1.0", path = "../crypto_common"}

# key and data export
base64ct = {version = "1.0.1", default-features = false, features = ["alloc"]}  # must use this version because it is not comp. with password_hash from argon2
pem-rfc7468 = {version = "0.3.1", features = ["alloc"]}

[features]
default = []
rust = []